language: android
sudo: false

env:
  global:
    - ADB_INSTALL_TIMEOUT=10

before_install:
- yes | sdkmanager "platforms;android-27"

android:
  components:
    - tools
    - platform-tools
    - tools

    # BuildTools version
    - build-tools-28.0.1

    - android-22
    # Compile version
    - android-26

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26
    - extra-android-support

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-26
    - sys-img-armeabi-v7a-android-17

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-22 --abi google_apis/armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew assembleRelease
  - ./gradlew assembleReleaseUnitTest
  - ./gradlew connectedAndroidTest
